INSERT INTO "LLMModels"
(
    "Id",
    "Name",
    "DisplayName",
    "Provider",
    "ModelCategory",
    "ModelFamily",
    "HostingType",
    "ParameterSizeBillion",
    "SupportsCodeGeneration",
    "SupportsToolCalling",
    "IsOpenSource",
    "IsEnterprise",
    "IsActive",
    "IsEnabled",
    "ModelUrl",
    "DocumentationUrl",
    "Description",
    "Tags",
    "CreatedAtUtc",
    "UpdatedAtUtc"
)
VALUES

(
    gen_random_uuid(),
    'deepseek-coder-v2',
    'DeepSeek Coder V2',
    'DeepSeek',
    'Code',
    'DeepSeek',
    'vLLM',
    236,
    true,
    true,
    true,
    true,
    true,
    true,
    'https://ollama.com/library/deepseek-coder',
    'https://huggingface.co/deepseek-ai',
    'Advanced coding and agentic software generation model.',
    'coding,agents,enterprise',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'qwen2.5-coder:32b',
    'Qwen 2.5 Coder',
    'Alibaba',
    'Code',
    'Qwen',
    'vLLM',
    32,
    true,
    true,
    true,
    true,
    true,
    true,
    'https://ollama.com/library/qwen2.5-coder',
    'https://huggingface.co/Qwen',
    'Enterprise coding model.',
    'coding,enterprise',
    NOW(),
    NOW()
);